# Generated by Django 2.2.5 on 2019-09-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name_plural': 'Статьи',
                'db_table': 'articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата конца')),
                ('place_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('place_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Уже скоро',
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст')),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст')),
                ('img_path', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Картинка')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'managed': False,
            },
        ),
    ]
